#!/usr/bin/env bash

set -eu

cd "${BASH_SOURCE%/*}"
basedir=$PWD

# target repository
target=${1:-archlinux}

docker run --rm --privileged -v "$basedir:/mnt" -w /mnt "$target" ./rootfs
docker build -t "$target" .
rm -f rootfs.tar
